### ISSUE TITLE
Unable to Download and Decode Large File via Git LFS

### ISSUE THREAD

**Issue by huiying-ying** [jpcsmith/qcsd-experiments#3]
Hello,  I am currently facing an issue with downloading and decoding a large file (alexa-1m-2021-07-18.csv.gz) from the repository using Git LFS. The file size is 4011360 bytes, and it seems that I am unable to download it due to data quota limitations.

When attempting to use git lfs pull to download the file, I encounter a data quota error. 

![2d1bb7e9c2a0f8456b9565901da05899](https://github.com/jpcsmith/qcsd-experiments/assets/61047589/8c8198f8-3280-49f6-99b8-4cce811a636c)

As a result, I am unable to access the file content and decode it for further processing.
It would be greatly appreciated if the data quota limitations for Git LFS could be reviewed and potentially increased to allow for the successful download of the large file. Alternatively, if there is a direct download link or alternative method to access the file content, I would be grateful for any guidance in this regard.

Thank you for your attention to this matter. I am looking forward to your assistance in resolving this issue.

**Comment by jpcsmith** [comment]
The quota has been increased. You should be able to download it now.

**Comment by SherrySu0222** [comment]
Thank you so much for resolving the issue. Your help means a lot to me. I truly appreciate it.
